apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: kcp-libs
  namespace: default
spec:
  branch: fix/openbao-no-default-issuer
  populate:
    partition: directory
    summarize: true
  source: {}
  verify:
  - go
  - test
  - ./...
status:
  contexts:
    failed: 0
    summarized: 44
    total: 44
  headCommit: 17c6ff5003e77e21dab4989a2c7fac201827c0e7
  indexedCommit: 17c6ff5003e77e21dab4989a2c7fac201827c0e7
  observedCommit: 17c6ff5003e77e21dab4989a2c7fac201827c0e7
  phase: Populated
  syncedCommit: 17c6ff5003e77e21dab4989a2c7fac201827c0e7
