apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: kcp-libs
  namespace: default
spec:
  branch: fix/openbao-no-default-issuer
  populate:
    partition: directory
    summarize: true
  source: {}
  verify:
  - go
  - test
  - ./...
status:
  contexts:
    failed: 0
    summarized: 44
    total: 44
  headCommit: f9e2ef3cfa3a9ae4d984768e8fce97092fe179bf
  indexedCommit: f9e2ef3cfa3a9ae4d984768e8fce97092fe179bf
  observedCommit: f9e2ef3cfa3a9ae4d984768e8fce97092fe179bf
  phase: Populated
