apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: Repository
metadata:
  name: kcp-libs
  namespace: default
spec:
  source: {}
  branch: fix/openbao-no-default-issuer
  verify:
  - go
  - test
  - ./...
  populate:
    partition: directory
    summarize: true
status:
  headCommit: 51a1c3e1cd2278b3d8a73e53795b2dc3faa0c5a8
  indexedCommit: 51a1c3e1cd2278b3d8a73e53795b2dc3faa0c5a8
  phase: Populated
  contexts:
    total: 44
    summarized: 44
    failed: 0
