apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: common-ttl-c2s-f6911d237e31-f6911d237e31
  namespace: default
spec:
  delta: {}
  direction: CodeToSpec
  fromCommit: f6911d237e3140ff2c6ff198b50189c07daa46d8
  systemContext: common-ttl
  toCommit: f6911d237e3140ff2c6ff198b50189c07daa46d8
status:
  message: the agent is summarizing common-ttl
  phase: Running
